spring:
  h2:
    console:
      enabled: true

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:subway

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
